#!/bin/sh
# Copyright PVT Solar Inc. 2008
#
# 
SCRIPT_REVISION="PVT Application Startup Script Revision 1.09"

/bin/echo "remounting root filesystem with noatime"
/bin/mount -o remount,rw,noatime /
/bin/sleep 10

trap "" 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22

PATH=/sbin:/bin:/usr/sbin:/usr/bin


echo "Creating temporary file system"
mount -t ramfs -o size=8m ramtmp /tmp
mkdir /tmp/logs
mkdir /tmp/pvt
chmod 777 /tmp/pvt

echo $SCRIPT_REVISION > /tmp/logs/applicationstartupversion.log

# USB Insurance Script
# Notes:
# 1) There are two parts to this script - one for PVT Solar and one for a field
#     installer
#    - PVT Solar will use two folders: From_Controller and To_Controller
#    - A field tech would use the Push_Configuration folder
# 2) This assumes the usb drive will mount as /dev/sda1 - is this always true
#     with our boards?
# 3) Warning: this script will pull everything from the /home/pvt directory and
#     push everything from the To_Controller folder to /home/pvt, overwriting
#     files if necessary
# 4) All files in the From_Controller folder will be erased (to prevent
#     confusion)
# 5) This script should probably stay intact in the applicationstart file
#     (rather than as its own file), as that will keep the pvt application from
#     starting before this script is done
#
# The logic for the LEDs:
# 1) no usb drive -> nothing happens
# 2) usb drive but not one of the three folders -> nothing happens
# 3) usb drive with either From_Controller or To_Controller -> copy files ...
#     flash green LEDs for each successful action (one or two)
# 4) usb drive with Push_Configuration -> flash green LEDs, if successful done
#     if not flash red LED

greenLED()
{
   for i in {1..10}
   do
      /initrd/bin/peekpoke 8 0x600ff08f 2 > /dev/null
      /initrd/bin/usleep 100000
      /initrd/bin/peekpoke 8 0x600ff08f 1 > /dev/null
      /initrd/bin/usleep 100000
   done
   /initrd/bin/peekpoke 8 0x600ff08f 0 > /dev/null
}

redLED()
{
   for i in {1..10}
   do
      /initrd/bin/peekpoke 8 0x600ff08f 4 > /dev/null 
      /initrd/bin/usleep 100000
      /initrd/bin/peekpoke 8 0x600ff08f 0 > /dev/null
      /initrd/bin/usleep 100000
   done
}

# Initialize memory for LEDs
#Row A GPIO
/initrd/bin/peekpoke 32 0x600ff098 0 > /dev/null
#Row B GPIO
/initrd/bin/peekpoke 32 0x600ff09c 0 > /dev/null
#Row B DDR Ouput
/initrd/bin/peekpoke 8 0x600ff097 7 > /dev/null
#Row A DDR Output
/initrd/bin/peekpoke 8 0x600ff093 3 > /dev/null

# Turn off LEDs 1, 2, and 3 (if they are on)
/initrd/bin/peekpoke 8 0x600ff08f 0 /dev/null

# Try to mount the flash drive
mount /dev/sda1 /mnt

# If the From_Controller folder is present, clean it and pull everything to it
if [ -d /mnt/From_Controller ]; then
   rm -r /mnt/From_Controller/* 
   cp -r /home/pvt/* /mnt/From_Controller && greenLED
fi

# If the To_Controller folder is present, put everything on it into the
#  /home/pvt folder
# Note: a log file is written to the stick that will show what was moved
if [ -d /mnt/To_Controller ]; then
   cp -v -f /mnt/To_Controller/* /home/pvt >& /mnt/Files_Copied_To_Controller.txt && sleep 2 && greenLED
fi

# This one is for the contractor and is very specific
if [ -d /mnt/Push_Configuration ]; then
   greenLED   
   cp -f /mnt/Push_Configuration/config.dat /home/pvt/config.dat || redLED
fi

if [ -f /mnt/pvtinit ]; then
   greenLED
   . /mnt/pvtinit
fi

# Cleanup
umount /mnt



# Starting PVT application and webservices

if uname -r | grep 2.6.24.4 > /dev/null
then
   echo Starting XUART 1
   /usr/local/bin/xuartctl --port=1 --server --speed=9600 --mode=8n1
   echo Starting XUART 2
   /usr/local/bin/xuartctl --port=2 --server --speed=9600 --mode=8n1
   echo Starting XUART 5
   /usr/local/bin/xuartctl --port=5 --server --speed=19200 --mode=8n1
fi

cd /home/pvt

/home/pvt/runotsmanager.sh
/home/pvt/runupdater.sh
/home/pvt/runpvt.sh &
/home/pvt/runws.sh &
if test -f /home/pvt/runwebsock.sh
then
   chmod 744 /home/pvt/runwebsock.sh
   /home/pvt/runwebsock.sh &
fi
